name: Maven Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Show tool versions
        run: |
          java -version
          mvn -v

      - name: Build & run tests
        run: mvn -B -DtrimStackTrace=true clean install

      - name: Upload surefire reports (unit tests)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: '**/target/surefire-reports/**'
          if-no-files-found: ignore

      - name: Upload failsafe reports (integration tests)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: failsafe-reports
          path: '**/target/failsafe-reports/**'
          if-no-files-found: ignore

      - name: Build Docker image
        uses: whoan/docker-build-with-cache-action@v8
        with:
           image_name: Dominikrex/SE-Konzepte
           push_image_and_stages: false